sources:
  - { kind: call, method: "@ptatest/entry/src/main/ets/pages/taint.ets: taint.genSource() : string", index: result }
  - { kind: param, method: "@ptatest/entry/src/main/ets/pages/taint.ets: taint.Source(string) : string", index: 0 }

sinks:
  - {method: "@ptatest/entry/src/main/ets/pages/taint.ets: taint.Sink(string) : void", index: 0}

transfers:
  - { method: "@ptatest/lib/lib.es5.d.ts: String.concat(string[]) : string", from: base, to: result }
  - { method: "@ptatest/lib/lib.es5.d.ts: String.concat(string[]) : string", from: 0, to: result }